### PR TITLE
Bridge event: fix Safari image sizing

### PR DESCRIPTION
**Pull request by etrepum**
I'm not entirely sure when this layout algorithm change happened in Safari but explicitly setting the image width to 100% fixes it. It seems to occur when the images are in a grid with object-fit.

As for the logo sizing it's currently based on a grid. It might make sense to pad some of the logos to fit in that grid better.
<details><summary>Screenshots of grid</summary>

Screen Shot 2021-07-12 at 1 12 52 PM
Screen Shot 2021-07-12 at 1 12 35 PM
</details>

### CODE REVIEW

**Comment by johnnylin629** [comment]
@etrepum, can you make the logos we have this year look like last year's grid layout? Right now it looks like this on mobile:

Screen Shot 2021-07-13 at 11 32 28 AM

Screen Shot 2021-07-13 at 11 32 40 AM

Screen Shot 2021-07-13 at 11 32 52 AM

**Comment by etrepum** [comment]
That’s not quite what it looks like in this review app https://deploy-preview-299--missionbit.netlify.app/bridge

ABB85107-F28C-4D38-9A92-11769DCFB458

We can probably normalize the sizes of the logos in this orientation by enforcing a maximum height, mostly so the square logos don’t take up so much space.

**Comment by johnnylin629** [comment]
Hmm, yeah it looks like the Verizon logo looks fine on the review app, but the Sponsors Logos look a little weird, I'v asked Notion for their logo with the icon they have and text so it'll match all the other logo setups we have currently.

image

**Comment by etrepum** [comment]
The logos are all different sizes because the logo files are different aspect ratios (e.g. most are wide, roughly 2:1 or 3:1 but notion's logo is close to 1:1). Also, some of the logos have internal padding and others don't. The more consistent the files are, the more consistent they will look on the page.

**Comment by johnnylin629** [comment]
What would the next best steps be? Putting them into Canva, then sizing them all the same?

**Comment by etrepum** [comment]
That would be one way to do it. I don't have any experience with canva but hopefully it can keep the files the same type (png or svg).

**Comment by johnnylin629** [comment]
Ok, thanks Bob! Is there a preferred size to have them at?

**Comment by etrepum** [comment]
The aspect ratio is what really matters, whatever size comfortably fits the most logos. Probably something like 2:1 or 3:1. It will look best if you only change the canvas size (add or remove space around the logo) and not scale the images.

**Comment by johnnylin629** [comment]
@etrepum I edited the logos to a 2:1 ratio, but it's still acting the same

image

**Comment by etrepum** [comment]
I think you're not looking at the right place, or maybe didn't wait for the deploy preview to be ready. The deploy preview is here https://deploy-preview-299--missionbit.netlify.app/bridge

**Comment by johnnylin629** [comment]
Ah oops, I was looking at 298's pull request's deploy. It looks like this rather than how it looked on last year's page

image

**Pull request merged**
