### PR TITLE
Donate page

### LINKED ISSUE #71: Implement new Donate page design

### PR DESCRIPTION
**Pull request by etrepum**
Resolves #71

Donate page

Example Testing URLs:

- [Donate Page](https://deploy-preview-70--missionbit.netlify.app/donate)
- [Receipt (one-time)](https://deploy-preview-70--missionbit.netlify.app/donate/result?session_id=cs_test_M7lTQ3uljLX4wqrO51DNQvw2bNw5vhwWIWmzWEoQFbeYJiOskfjY6o9x)
- [Receipt (monthly)](https://deploy-preview-70--missionbit.netlify.app/donate/result?session_id=cs_test_qBHGWPr4BLpXKogpWsCYabY59XSH7BWVcEAN6I37wNZjOYR85uZQGqgm)
- [Manage subscription (canceled)](https://deploy-preview-70--missionbit.netlify.app/donate/subscriptions/sub_HY9Uh4Jl2dUOJZ)
- [Manage subscription](https://deploy-preview-70--missionbit.netlify.app/donate/subscriptions/sub_HWekwo4LowPOD8)

Since Stripe is in test mode for this PR (and local development), you can use the test card `4242 4242 4242 4242` to initiate new transactions. It will accept any future expiration date, name, zip, and CVC. See also https://stripe.com/docs/testing#cards

Design TODO:

- [x] for the pictures at the bottom, could we make them fill up the entire width of the screen? maybe just making them bigger? also, could we have the same space at the bottom as they do between each other?
- [x] the content could be a bit more spread out horizontally-wise, there's a bit too much room on either side, but not enough between (support our work & make an online gift, learn more & other ways to give)
- [x] for the donation box, the "one-time" and "monthly" buttons have really small text, I think it needs to be same size as the $250, 100, 50.
- [x] the p text seems very small, can we make it a bit bigger on the entire page? maybe it's in contrast with the headings...
- [x] same with the button "get in touch with us" -- could be a bit bigger.
- [x] same with "Amount"-- it's even teenier

### CODE REVIEW

**Comment by abhay** [comment]
There seems to be a bug somewhere in the cancellation flow. First time I tried to cancel a subscription, I got a 500. Will drop a screen recording in slack.

**Comment by abhay** [comment]
Unrelated to above. First time I try to donate, I get an error as well 

```
{"statusCode":500,"message":"An error occurred with our connection to Stripe."}```

**Comment by abhay** [comment]
Maybe it's my browser but first time I pay... 

https://deploy-preview-70--missionbit.netlify.app/donate/result?session_id=cs_test_NJVVEIRUulyVhYrhe6sIDyOFpEnvhQq8oJSlE3oadAYQdL9Ts19JJ1FX

throws an HTML 500 page as well

Refresh the page and I get the donation receipt page.

**Comment by etrepum** [comment]
Must be an issue with Netlify's version of node.js, it all works locally of course. Thanks for doing QA 👍

**Comment by etrepum** [comment]
Seems like some kind of hopefully intermittent issue somewhere between Netlify and Stripe?

<details>
<summary>Traceback</summary>

```
9:41:16 AM: 2020-06-29T16:41:16.934Z	16bd2b58-6b4a-4582-932e-8987f94c0527	ERROR	StripeConnectionError: An error occurred with our connection to Stripe.
    at /var/task/src/out_functions/next_donate_result/nextJsPage.js:1516:9
    at ClientRequest.<anonymous> (/var/task/src/out_functions/next_donate_result/nextJsPage.js:1771:67)
    at ClientRequest.emit (events.js:310:20)
    at TLSSocket.socketOnEnd (_http_client.js:453:9)
    at TLSSocket.emit (events.js:322:22)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  type: 'StripeConnectionError',
  raw: {
    message: 'An error occurred with our connection to Stripe.',
    detail: Error: socket hang up
        at connResetException (internal/errors.js:608:14)
        at TLSSocket.socketOnEnd (_http_client.js:453:23)
        at TLSSocket.emit (events.js:322:22)
        at endReadableNT (_stream_readable.js:1187:12)
        at processTicksAndRejections (internal/process/task_queues.js:84:21) {
      code: 'ECONNRESET'
    }
  },
  rawType: undefined,
  code: undefined,
  doc_url: undefined,
  param: undefined,
  detail: Error: socket hang up
      at connResetException (internal/errors.js:608:14)
      at TLSSocket.socketOnEnd (_http_client.js:453:23)
      at TLSSocket.emit (events.js:322:22)
      at endReadableNT (_stream_readable.js:1187:12)
      at processTicksAndRejections (internal/process/task_queues.js:84:21) {
    code: 'ECONNRESET'
  },
  headers: undefined,
  requestId: undefined,
  statusCode: undefined,
  charge: undefined,
  decline_code: undefined,
  payment_intent: undefined,
  payment_method: undefined,
  setup_intent: undefined,
  source: undefined
}
```
</details>

**Comment by etrepum** [comment]
On further investigation it seems the root cause of the bug was trusting that the Stripe API would work 100% of the time ;) We're lucky to have caught this now!

**Comment by abhay** [comment]
Amazing

**Pull request merged**
