### PR TITLE
Add a desktop hover menu for programs sections

### PR DESCRIPTION
**Pull request by etrepum**
RE #215

### CODE REVIEW

**Comment by coramonokandilos** [comment]
Looks good! One thing -- is it possible to remove the shadow or make it a little bit less on the top? 
Screen Shot 2020-12-10 at 10 28 06 AM

**Comment by etrepum** [comment]
We can do whatever we want with the style but I don't quite understand what you want it to look like, can you give me a mockup of what you want?

**Comment by coramonokandilos** [comment]
I put a screenshot of a mockup I made in the comment I left earlier. 
Just for the top of the expanded menu to not have a shadow so it's not as harsh of a jump from the regular nav to the expanded nav. Your example here for reference: 
Screen Shot 2020-12-10 at 4 03 42 PM

**Comment by etrepum** [comment]
Got it, wasn't clear what the screenshot was since there wasn't much context in the comment

**Pull request merged**
